[program:scoreboard-emulated]
command=/home/pi/nhlsb-venv/bin/python3 ./src/main.py --emulated --updatecheck
directory=/home/pi/nhl-led-scoreboard
autostart=false
autorestart=true
stderr_logfile=/var/log/scoreboard-emulated.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stdout_logfile=/var/log/scoreboard-emulated.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10

# Don't restart too quickly if it keeps failing
startretries=3
startsecs=5

# Kill process gracefully (SIGTERM) before forcing (SIGKILL)
stopwaitsecs=10
stopsignal=TERM