#!/bin/bash

# Functionality will be moved into the scoreboard and pushbutton to trigger a reset
#python3 /usr/lib/raspiwifi/reset_device/reset.py &

python3 /usr/lib/raspiwifi/reset_device/connection_monitor.py &
