-
# Setup for scoreboard
 name: Scoreboard setup
 become: true
 become_user: pi
 vars:
  gh_repo: "https://github.com/riffnshred/nhl-led-scoreboard.git"
  use_beta: false
  gh_branch: "beta"

 tasks:

  - name: Copy sbtools directory
    ansible.builtin.copy:
     src: files/sb_image/sbtools
     dest: ~/
     mode: preserve

  - name: Copy config neofetch directory
    ansible.builtin.copy:
     src: files/config
     dest: ~/.config
     mode: "0755"

  - name: Create .nhlledportal directory
    ansible.builtin.file:
     path: ~/.nhlledportal
     state: directory
     mode: "0755"

  - name: Create startup files in .nhlledportal
    ansible.builtin.file:
     path: "~/.nhlledportal/{{ item }}"
     state: touch
     mode: "0755"
    with_items:
     - setTZ
     - SETUP

  - name: Create cron.scoreboard directory
    become_user: root
    ansible.builtin.file:
     path: /etc/cron.scoreboard
     state: directory
     mode: "0755"
