name: Create Release - Image

on:
   workflow_dispatch:  
   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Get the version (git tag)
      uses: maltoze/get-version-action@v1
      id: get_version
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build scoreboard image
      run: |
        docker run --rm --privileged -v /dev:/dev -v ${PWD}/nhl-image:/build ghcr.io/falkyre/packer-arm-ansible:latest build raspios.pkr.hcl
        du -h nhl-image/rpios-scoreboard.img
        du -h --apparent-size nhl-image/rpios-scoreboard.img

    - name: Compress image using pishrink
      run: |
        docker run --privileged=true --rm --volume ${PWD}/nhl-image/:/workdir mgomesborges/pishrink pishrink -aZv rpios-scoreboard.img

    - name: Rename compressed image to include version
      run: |
        cp nhl-image/rpios-scoreboard.img.xz rpios-scoreboard-${{ steps.get_version.outputs.version }}.img.xz
  
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          rpios-scoreboard-${{ steps.get_version.outputs.version }}.img.xz
