name: Create Release - Image

on:
   workflow_dispatch:  
   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get the version (git tag)
      id: get_version
      run: |
        echo ${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build scoreboard image
      run: |
        docker run --rm --privileged -v /dev:/dev -v ${PWD}/nhl-image:/build ghcr.io/falkyre/packer-arm-ansible:latest build raspios.pkr.hcl
        du -h rpios-scoreboard-${{ steps.get_version.outputs.VERSION }}.img
        du -h --apparent-size rpios-scoreboard-${{ steps.get_version.outputs.VERSION }}.img
  
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          rpios-scoreboard-${{ steps.get_version.outputs.VERSION }}.img.xz

    #- uses: sarisia/actions-status-discord@v1
    #  with:
    #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
    #    nodetail: true
    #    title: New version of `NHL LED Scoreboard image` is ready!
    #    description: |
    #      Version `${{ steps.get_version.outputs.VERSION }}`
    #      Click [here](https://github.com/falkyre/nhl-led-scoreboard-img/releases/latest) to download!
    #- uses: sarisia/actions-status-discord@v1
    #  with:
    #    webhook: ${{ secrets.NHLDISCORD_WEBHOOK }}
    #    nodetail: true
    #    title: New version of `NHL LED Scoreboard image` is ready!
    #    description: |
    #      Version `${{ steps.get_version.outputs.VERSION }}`
    #      Click [here](https://github.com/falkyre/nhl-led-scoreboard-img/releases/latest) to download!
    # - name: Upload Image
    #   id: upload-release-asset 
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: deploy/image_rpios-scoreboard.zip
    #     asset_name: rpios-scoreboard-${{ steps.get_version.outputs.VERSION }}.zip
    #     asset_content_type: application/zip
