name: Create Release - Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      run_type:
        description: 'Run type: "Test" or "Release"'
        required: true
        default: 'Test'
        type: choice
        options:
        - Test
        - Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get the version (git tag)
      uses: maltoze/get-version-action@v1
      id: get_version

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build scoreboard image
      run: |
        docker run --rm --privileged -v /dev:/dev -v ${PWD}/nhl-image:/build ghcr.io/falkyre/packer-arm-ansible:latest build raspios_trixie.pkr.hcl
        du -h nhl-image/rpios-scoreboard.img
        du -h --apparent-size nhl-image/rpios-scoreboard.img

    - name: Rename compressed image to include version
      run: |
        cp nhl-image/rpios-scoreboard.img.xz rpios-scoreboard-${{ steps.get_version.outputs.version }}.img.xz

    - name: Create changelog text
      id: changelog
      uses: loopwerk/tag-changelog@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude_types: other,doc,chore

    - name: Upload image artifact for testing
      if: github.event.inputs.run_type == 'Test'
      uses: actions/upload-artifact@v4
      with:
        name: rpios-scoreboard-${{ steps.get_version.outputs.version }}.img
        path: rpios-scoreboard-${{ steps.get_version.outputs.version }}.img.xz

    - name: GH Release
      if: github.event.inputs.run_type == 'Release' || github.event_name == 'push'
      uses: softprops/action-gh-release@v0.1.15
      with:
        prerelease: true
        generate_release_notes: true
        body: ${{ steps.changelog.outputs.changes }}
        files: rpios-scoreboard-${{ steps.get_version.outputs.version }}.img.xz

