name: Create Release - Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  
   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Get the version (git tag)
      uses: maltoze/get-version-action@v1
      id: get_version
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build scoreboard image
      run: |
        docker run --rm --privileged -v /dev:/dev -v ${PWD}/nhl-image:/build ghcr.io/falkyre/packer-arm-ansible:latest build raspios.pkr.hcl
        du -h nhl-image/rpios-scoreboard.img
        du -h --apparent-size nhl-image/rpios-scoreboard.img

    - name: Rename compressed image to include version
      run: |
        cp nhl-image/rpios-scoreboard.img.xz rpios-scoreboard-${{ steps.get_version.outputs.version }}.img.xz

    - name: Create changelog text
      id: changelog
      uses: loopwerk/tag-changelog@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude_types: other,doc,chore

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        prerelease: true
        generate_release_notes: true
        body: ${{ steps.changelog.outputs.changes }}
        files: rpios-scoreboard-${{ steps.get_version.outputs.version }}.img.xz

