# This is a basic workflow to help you get started with Actions

name: Notify - Discord

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
       version:
         description: 'Version Release'
         required: true
         default: 'v1.6.0'
       detail:
         description: 'Extra Notes'
         required: false
         default: 'Excelsior!'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Notify-Discord:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        nodetail: true
        title: New version of `NHL LED Scoreboard image` is ready!
        description: |
          Version `${{ github.event.inputs.version }}`
          Click [here](https://github.com/falkyre/nhl-led-scoreboard-img/releases/latest) to download!
          ----
          Extra Notes: 
          ${{ github.event.inputs.detail }}
    - uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.NHLDISCORD_WEBHOOK }}
        nodetail: true
        title: New version of `NHL LED Scoreboard image` is ready!
        description: |
          Version `${{ github.event.inputs.version }}`
          Click [here](https://github.com/falkyre/nhl-led-scoreboard-img/releases/latest) to download!
          ----
          Extra Notes: 
          ${{ github.event.inputs.detail }}
