name: publish packer-arm-ansible

on: 
   workflow_dispatch:

jobs:
     publish-image:
       runs-on: ubuntu-latest

       steps:
         - name: 'Checkout GitHub Action'
           uses: actions/checkout@v4
        
         - name: Set up QEMU
           uses: docker/setup-qemu-action@v3

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Login to GitHub Container Registry
           uses: docker/login-action@v3
           with:
             registry: ghcr.io
             username: ${{ github.actor }}
             password: ${{ secrets.GITHUB_TOKEN }}
             
        #  - name: Build the packer-arm-ansible image
        #    run: |
        #      docker build . --tag ghcr.io/falkyre/packer-arm-ansible:latest --tag ghcr.io/falkyre/packer-arm-ansible:1.0.8
        #      docker push ghcr.io/falkyre/packer-arm-ansible:latest

          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              platforms: linux/amd64,linux/arm64
              push: true
              tags: falkyre/packer-arm-ansible:latest
