name: publish

on: 
   workflow_dispatch:

jobs:
     publish-image:
       runs-on: ubuntu-latest

       steps:
         - name: 'Checkout GitHub Action'
           uses: actions/checkout@v2
         
         - name: Login to GitHub Container Registry
           uses: docker/login-action@v1
           with:
             registry: ghcr.io
             username: ${{ github.actor }}
             password: ${{ secrets.GITHUB_TOKEN }}
             
         - name: Build the park-arm-ansible image
           run: |
             docker build . --tag ghcr.io/falkyre/packer-arm-ansible:latest
             docker push ghcr.io/falkyre/packer-arm-ansible:latest